// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjBwcM07AxcMX9zW76acL53PNMQwOwlQ',
    appId: '1:1041900101887:web:728d2755838d55b65c6cca',
    messagingSenderId: '1041900101887',
    projectId: 'teensofgod-6c42b',
    authDomain: 'teensofgod-6c42b.firebaseapp.com',
    storageBucket: 'teensofgod-6c42b.appspot.com',
    measurementId: 'G-JH9Z6968JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBldzBLIwoRH75GtKPCxCvXVAS0i0UrdhE',
    appId: '1:1041900101887:android:221ee06afe16a6c35c6cca',
    messagingSenderId: '1041900101887',
    projectId: 'teensofgod-6c42b',
    storageBucket: 'teensofgod-6c42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyd22XDoDSJ2ayFJ1Rz1H4LbXiT0B1IM',
    appId: '1:1041900101887:ios:2f6626a7ce6782c95c6cca',
    messagingSenderId: '1041900101887',
    projectId: 'teensofgod-6c42b',
    storageBucket: 'teensofgod-6c42b.appspot.com',
    iosClientId: '1041900101887-ppok5t83ujep3ecdc8np0esbp72cnpj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.teensOfGod',
  );
}
